version: '3.8'
services:

  mrm_info_proxy:
    container_name: mrm_info_proxy
    build: ./
    restart: always
    ports:
      - "7403:7403"
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - MRMSUPPORTBOT_AUTH_LOGIN="login"
      - MRMSUPPORTBOT_AUTH_PASSWORD="password"
      - MRMSUPPORTBOT_TOKEN="token"
    volumes:
      - /etc/letsencrypt/live/service.icecorp.ru-0001/fullchain.pem:/cert/fullchain.pem
      - /etc/letsencrypt/live/service.icecorp.ru-0001/privkey.pem:/cert/privkey.pem
      - /mnt/soft:/mnt/soft