version: '3.8'
services:

  mrm_support_bot:
    container_name: mrm_support_bot
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/yurasov/projects/iceberg_telegram/data/:/server/data
      # - ./data:/server/data
      # - /mnt/photos:/mnt/photos
      - /mnt/soft:/mnt/soft
      - ./config.json:/server/config.json
    build: ./
    ports:
      - "7404:84"
    environment:
      - TZ=Europe/Moscow
      - MRMSUPPORTBOT_AUTH_LOGIN=login
      - MRMSUPPORTBOT_AUTH_PASSWORD=password
      
  mrm_support_bot_test:
    container_name: mrm_support_bot_test
    # restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/yurasov/projects/iceberg_telegram/data:/server/data
      - ./config_test.json:/server/config.json
      # - ./data:/server/data
      # - /mnt/photos:/mnt/photos
      - /mnt/soft:/mnt/soft
    build: ./
    ports:
      - "7405:84"
    environment:
      - TZ=Europe/Moscow
      - MRMSUPPORTBOT_AUTH_LOGIN=login
      - MRMSUPPORTBOT_AUTH_PASSWORD=password