version: '3.8'
services:

  mrm_support_bot: 
    container_name: mrm_support_bot
    # restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/server/data
      - /mnt/soft:/mnt/soft
    build: ./
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - MRMSUPPORTBOT_AUTH_LOGIN=login
      - MRMSUPPORTBOT_AUTH_PASSWORD=password
      